# -*- coding: utf-8 -*-
"""2.1-Variáveis-Exercícios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10i05XHVsDmnkg5eBrBS7-Tg_XhH58x1z

# Módulo 2
## 2.1 Variáveis

### Q1.
Selecione todos os itens a seguir que contém nomes válidos de variáveis. Lembre-se que alguns nomes com estrutura válida são palavras reservadas da linguagem e portanto não podem nomear variáveis.

    a) nome_completo
    b) quantidade@produtos
    c) idade
    d) soma idades
    e) MediaNotas
    f) _tipo
    g) 2total
    h) lambda
"""

# Preencha o print com as alternativas corretas
# separadas por espaços em branco.
# Ex: print("a b c")
print("a,c,f ")

"""---
### Q2.
Dados os scripts a seguir, faça:
- Para os scripts corretos escreva o resultado impresso ao final da execução
- Para os incorretos descreva todos os erros identificados apontando a linha onde cada erro acontece.

```python
# Script 1
x = 10
y = x + 2
print(y - 5)
```
"""

# preencha o print com sua resposta
print("7")

"""```python
# Script 2
soma = n1 + n2
print(soma)
```
"""

# preencha o print com sua resposta
print("Erro na linha 1: n1 e n2 não definidos (NameError)")

"""```python
# Script 3
a = 10
a = a + 1
print(a)
```
"""

# preencha o print com sua resposta
print("11")

"""```python
# Script 4
saldo da conta = 1500
0.1 = juros
print(saldo da conta * juros)
```
"""

# preencha o print com sua resposta
print("Erros: linha 1 (nome de variável inválido), linha 2 (atribuição inválida, vírgula usada em vez de ponto) ")

"""---
### Q3.
Declare três variáveis, `num1`, `num2` e `num3`, com yvalores inteiros numéricos de sua escolha. Calcule e imprima a média desses três números. Utilize a fórmula: `(num1 + num2 + num3) / 3`.
"""

print((10 + 20 + 30) / 3)

"""---
### Q4.
Escreva um script python que:
- Armazene em uma variável uma velocidade de 90 km/h
- Calcule e armazene o equivalente em m/s
    - Divida o valor original por 3.6 para obter o resultado em m/s. Em python a sintaxe da divisão e atribuição é c = a / b
- Imprima na tela a velocidade o resultado m/s

"""

velocidade_kmh = 90
velocidade_m_s = velocidade_kmh / 3.6
print("A velocidade em m/s é:", velocidade_m_s)

"""---
### Q5.
Escreva um script python que:
- Armazene o seu nome em uma variável
    - Dica: para armazenar textos em variáveis basta colocar a palavra desejada entre aspas, ex: "Camila", à direita do operador de atribuição.
- Imprima o texto "Meu nome é:"
- Imprima a variável com seu nome

"""

# Armazena o nome em uma variável
meu_nome = "Kethelyn"

# Imprime o texto
print("Meu nome é:")

# Imprime o conteúdo da variável
print(meu_nome)